name = "RAI"
uuid = "9c30249a-7e08-11ec-0e99-a323e937e79f"
version = "0.0.4"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArgParse = "1"
Arrow = "2"
ConfParser = "0.1"
HTTP = "1.0"
JSON3 = "1"
Tables = "1"
Mocking = "0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
